title: "DSC259 Final Project: Power Outages"
author: "Scotty, Hans, and [Group Member 3]" # Better for multiple names
email: "rsrogers@ucsd.edu" # Keep to a single primary email to avoid breaking mailto: links
description: >-
  Following the data science lifecycle for major power outage risk in the U.S.
url: "[https://scotty-ucsd.github.io](https://scotty-ucsd.github.io)"
baseurl: "/dsc259_final_project_rsrogers"
twitter_username: ""
github_username: "scotty-ucsd"

# Build settings
markdown: kramdown
